{{- if .Values.global.clusterd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterd.fullname" . }}
  labels:
    {{- include "clusterd.labels" . | nindent 4 }}
data:
  clusterd.yaml: |
{{ tpl (.Files.Get "src/config/clusterd.yaml") . | nindent 4 }}
{{- end }}
