{{- if .Values.global.dlpd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dlpd.fullname" . }}
  labels:
    {{- include "dlpd.labels" . | nindent 4 }}
data:
  dlpd.yaml: |
{{ tpl (.Files.Get "src/config/dlpd.yaml") . | nindent 4 }}
  dlpd-app.yaml: |-
{{ tpl (.Files.Get "src/config/dlpd-app.yaml") . | nindent 4 }}
  dlpctl.yaml: |
{{ tpl (.Files.Get "src/config/dlpctl.yaml") . | nindent 4 }}
{{- end }}