apiVersion: v2
name: main
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: clusterd
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: policyd
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: dlpd
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: rated
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: sasid
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: savdid
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: expurgate
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: smtpd
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: web
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"
  - name: classifier
    version: 0.1.0
    repository: "apprelaypoccontreg.azurecr.io/helm"