{{- if .Values.global.smtpd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smtpd.fullname" . }}-config
  labels:
    {{- include "smtpd.labels" . | nindent 4 }}
data:
  smtpd.yaml: |
{{ tpl (.Files.Get "src/config/smtpd.yaml") . | nindent 4 }}
  smtpd-app.yaml: |
{{ tpl (.Files.Get "src/config/smtpd-app.yaml") . | nindent 4 }}
  api.yaml: |
{{ tpl (.Files.Get "src/config/api.yaml") . | nindent 4 }}
  smtpd-policy.yaml: |
{{ tpl (.Files.Get "src/config/smtpd-policy.yaml") . | nindent 4 }}
  smtpd-delivery.yaml: |
{{ tpl (.Files.Get "src/config/smtpd-delivery.yaml") . | nindent 4 }}
{{- $root := . }}
{{- $hookSubfolders := list "eod" "auth" "connect" "disconnect" "helo" "mailfrom" "proxy" "queue" "rcptto" }}
{{- range $hook := $hookSubfolders }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smtpd.fullname" $root }}-hooks-{{ $hook }}
  labels:
    {{- include "smtpd.labels" $root | nindent 4 }}
{{- $hookFiles := $root.Files.Glob (printf "src/hooks/%s/**" $hook) }}
{{- if $hookFiles }}
data:
{{- range $path, $_ := $hookFiles }}
  {{ base $path }}: |
{{ tpl ($root.Files.Get $path) $root | nindent 4 }}
{{- end }}
{{- else }}
data: {}
{{- end }}
{{- end }}
{{- end }}