{{- if .Values.global.rated.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rated.fullname" . }}
  labels:
    {{- include "rated.labels" . | nindent 4 }}
data:
  rated.yaml: |
{{ tpl (.Files.Get "src/config/rated.yaml") . | nindent 4 }}
  rated-app.yaml: |
{{ tpl (.Files.Get "src/config/rated-app.yaml") . | nindent 4 }}
  ratectl.yaml: |
{{ tpl (.Files.Get "src/config/ratectl.yaml") . | nindent 4 }}
  api.yaml: |
{{ tpl (.Files.Get "src/config/api.yaml") . | nindent 4 }}
{{- end }}