{{- if .Values.global.web.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  web.yaml: |
{{ tpl (.Files.Get "src/config/web.yaml") . | nindent 4 }}
  web-history.yaml: |
{{ tpl (.Files.Get "src/config/web-history.yaml") . | nindent 4 }}
{{- end }}
