{{- if .Values.global.sasid.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sasid.fullname" . }}
  labels:
    {{- include "sasid.labels" . | nindent 4 }}
data:
  sasid.conf: |
{{ tpl (.Files.Get "src/config/sasid.conf") . | nindent 4 }}
{{- end }}