{{- if .Values.global.expurgate.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expurgate.fullname" . }}
  labels:
    {{- include "expurgate.labels" . | nindent 4 }}
binaryData:
  # Replace this sample data with your own base64 encoded license key
  client.key: |
    QUFBQkJCQ0ND
data:
  expurgate-spamd.conf: |
{{ tpl (.Files.Get "src/config/expurgate-spamd.conf") . | nindent 4 }}
{{- end }}
